name: phos
description: A custom UBlue image for my own personal usage
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40

modules:

# RPMFusion ------------------------------------------------------------------
  - type: bling
    install:
      - rpmfusion

# First-party RPM packages ---------------------------------------------------

  - type: rpm-ostree
    install:
      - btrfs-assistant
      - firewall-config
      - gh
      - guake
      - gnome-backgrounds-extras
      - igt-gpu-tools
      - intel-vsc-firmware
      - nautilus-python
      - neovim
      - ripgrep
      - seahorse-nautilus
      - slirp4netns
      - solaar
      - steam-devices
      - sushi
      - zsh

# Third-party RPM packages ---------------------------------------------------

  # firefoxpwa
  - type: script
    scripts:
      - add-firefoxpwa-repo.sh
  - type: rpm-ostree
    install:
      - firefoxpwa

  # hblock
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/hblock/repo/fedora-%OS_VERSION%/pesader-hblock-fedora-%OS_VERSION%.repo
    install:
      - hblock

  # showmethekey
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/showmethekey/repo/fedora-%OS_VERSION%/pesader-showmethekey-fedora-%OS_VERSION%.repo
    install:
      - showmethekey

# Miscellaneous installation methods -----------------------------------------

  # awatcher (shell script)
  - type: script
    scripts:
      - install-awatcher.sh

# Flatpaks -------------------------------------------------------------------

  - type: default-flatpaks
    user:
      install:
        - app.devsuite.Ptyxis
        - app.drey.KeyRack
        - app.drey.Warp
        - ca.desrt.dconf-editor
        - com.belmoussaoui.Authenticator
        - com.belmoussaoui.Decoder
        - com.belmoussaoui.Obfuscate
        - com.bitwarden.desktop
        - com.github.ADBeveridge.Raider
        - com.github.hluk.copyq
        - com.github.huluti.Curtail
        - com.github.jeromerobert.pdfarranger
        - com.github.maoschanz.drawing
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.mardojai.ForgeSparks
        - com.mattjakeman.ExtensionManager
        - com.obsproject.Studio
        - com.stremio.Stremio
        - com.vscodium.codium
        - de.haeckerfelix.Fragments
        - garden.jamie.Morphosis
        - io.github.flattool.Warehouse
        - io.github.hrkfdn.ncspot
        - io.github.mpobaschnig.Vaults
        - io.github.lo2dev.Echo
        - io.github.nokse22.Exhibit
        - io.github.nokse22.inspector
        - io.github.seadve.Kooha
        - io.github.seadve.Mousai
        - io.github.slgobinath.SafeEyes
        - io.gitlab.adhami3310.Converter
        - io.gitlab.adhami3310.Impression
        - io.gitlab.theevilskeleton.Upscaler
        - io.typora.Typora
        - it.mijorus.collector
        - it.mijorus.gearlever
        - it.mijorus.smile
        - md.obsidian.Obsidian
        - me.dusansimic.DynamicWallpaper
        - me.iepure.devtoolbox
        - net.nokyan.Resources
        - nl.hjdskes.gcolor3
        - org.chromium.Chromium
        - org.gabmus.whatip
        - org.gnome.Builder
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.PowerStats
        - org.gnome.Shotwell
        - org.gnome.Showtime
        - org.gnome.Weather
        - org.gnome.World.PikaBackup
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.design.IconLibrary
        - org.gnome.design.Palette
        - org.gnome.design.SymbolicPreview
        - org.gnome.dspy
        - org.gnome.gitlab.YaLTeR.VideoTrimmer
        - org.gnome.gitlab.cheywood.Buffer
        - org.gnome.seahorse.Application
        - org.inkscape.Inkscape
        - org.libreoffice.LibreOffice
        - page.codeberg.libre_menu_editor.LibreMenuEditor

# Bundles --------------------------------------------------------------------

  # Pods (depends on podman-remote)
  - type: rpm-ostree
    install:
      - podman-remote
  - type: default-flatpaks
    user:
      install:
        - com.github.marhkb.Pods

  # Vaults (depends on gocryptfs)
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/gocryptfs/repo/fedora-%OS_VERSION%/pesader-gocryptfs-fedora-%OS_VERSION%.repo
    install:
      - gocryptfs
  - type: default-flatpaks
    user:
      install:
        - io.github.mpobaschnig.Vaults

# GTK3 theme -----------------------------------------------------------------

  - type: rpm-ostree
    install:
      - adw-gtk3-theme

  - type: default-flatpaks
    user:
      install:
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: gschema-overrides
    include:
      - zz1-adw-gtk3.gschema.override

# Icon theme -----------------------------------------------------------------

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/dusansimic/themes/repo/fedora-%OS_VERSION%/dusansimic-themes-fedora-%OS_VERSION%.repo
    install:
      - morewaita-icon-theme

# Shell tools ----------------------------------------------------------------

  # fzf
  - type: rpm-ostree
    install:
      - fzf
  - type: files
    files:
      - source: system/usr/etc/profile.d/fzf.sh
      - destination: /usr/etc/profile.d/fzf.sh

  # zoxide
  - type: rpm-ostree
    install:
      - zoxide
  - type: files
    files:
      - source: system/usr/etc/profile.d/zoxide.sh
      - destination: /usr/etc/profile.d/zoxide.sh

# GNOME Shell Extensions -----------------------------------------------------

  # App Icons Taskbar
  - type: gnome-extensions
    install:
      - App Icons Taskbar
  - type: gschema-overrides
    include:
      - zz1-aztaskbar.gschema.override

  # AppIndicator and KStatusNotifierItem Support
  - type: gnome-extensions
    install:
      - AppIndicator and KStatusNotifierItem Support
  - type: gschema-overrides
    include:
      - zz1-appindicator.gschema.override

  # Caffeine
  - type: gnome-extensions
    install:
      - Caffeine
  - type: gschema-overrides
    include:
      - zz1-caffeine.gschema.override

  # Dim Completed Calendar Events
  - type: gnome-extensions
    install:
      - Dim Completed Calendar Events
  - type: gschema-overrides
    include:
      - zz1-dim-completed-calendar-events.gschema.override

  # Focus changer
  - type: gnome-extensions
    install:
      - Focus changer
  - type: gschema-overrides
    include:
      - zz1-focus-changer.gschema.override

  # Hot Edge
  - type: gnome-extensions
    install:
      - Hot Edge
  - type: gschema-overrides
    include:
      - zz1-hotedge.gschema.override

  # Just Perfection
  - type: gnome-extensions
    install:
      - Just Perfection
  - type: gschema-overrides
    include:
      - zz1-just-perfection.gschema.override

  # Quick Close in Overview
  - type: gnome-extensions
    install:
      - Quick Close in Overview
  - type: gschema-overrides
    include:
      - zz1-middleclickclose.gschema.override

  # Lock Keys
  - type: gnome-extensions
    install:
      - 36
  - type: gschema-overrides
    include:
      - zz1-lockkeys.gschema.override

  # GSConnect
  - type: rpm-ostree
    install:
      - gnome-shell-extension-gsconnect
  - type: gschema-overrides
    include:
      - zz1-gsconnect.gschema.override

# Dotfiles -------------------------------------------------------------------

  - type: chezmoi
    repository: https://github.com/pesader/dotfiles

# GSettings ------------------------------------------------------------------

  - type: gschema-overrides
    include:
      - zz1-basics.gschema.override

# Signing policy -------------------------------------------------------------

  - type: signing
