name: phos
description: A custom UBlue image for my own personal usage
base-image: ghcr.io/ublue-os/silverblue-surface
image-version: 40

modules:

# Akmods ---------------------------------------------------------------------

  - type: akmods
    install:
      - v4l2loopback

# First-party RPM packages ---------------------------------------------------

  - type: rpm-ostree
    install:
      - adw-gtk3-theme
      - btrfs-assistant
      - firewall-config
      - gh
      - guake
      - gnome-network-displays
      - gnome-backgrounds-extras
      - igt-gpu-tools
      - intel-vsc-firmware
      - nautilus-python
      - neovim
      - ripgrep
      - seahorse-nautilus
      - slirp4netns
      - steam-devices
      - sushi
      - zsh

# Third-party RPM packages ---------------------------------------------------

  # firefoxpwa
  - type: script
    scripts:
      - add-firefoxpwa-repo.sh
  - type: rpm-ostree
    install:
      - firefoxpwa

  # hblock
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/hblock/repo/fedora-%OS_VERSION%/pesader-hblock-fedora-%OS_VERSION%.repo
    install:
      - hblock

  # showmethekey
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/showmethekey/repo/fedora-%OS_VERSION%/pesader-showmethekey-fedora-%OS_VERSION%.repo
    install:
      - showmethekey

# Miscellaneous installation methods -----------------------------------------

  # awatcher (shell script)
  - type: script
    scripts:
      - install-awatcher.sh

# Flatpaks -------------------------------------------------------------------

  - type: default-flatpaks
    user:
      install:
        - app.drey.Warp
        - ca.desrt.dconf-editor
        - com.belmoussaoui.Authenticator
        - com.belmoussaoui.Decoder
        - com.belmoussaoui.Obfuscate
        - com.bitwarden.desktop
        - com.github.ADBeveridge.Raider
        - com.github.finefindus.eyedropper
        - com.github.hluk.copyq
        - com.github.huluti.Curtail
        - com.github.jeromerobert.pdfarranger
        - com.github.maoschanz.drawing
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.mardojai.ForgeSparks
        - com.mattjakeman.ExtensionManager
        - com.obsproject.Studio
        - com.rafaelmardojai.SharePreview
        - com.stremio.Stremio
        - de.haeckerfelix.Fragments
        - io.dbeaver.DBeaverCommunity
        - io.github.celluloid_player.Celluloid
        - io.github.f3d_app.f3d
        - io.github.flattool.Warehouse
        - io.github.hrkfdn.ncspot
        - io.github.nokse22.inspector
        - io.github.seadve.Kooha
        - io.github.slgobinath.SafeEyes
        - io.gitlab.adhami3310.Converter
        - io.gitlab.adhami3310.Impression
        - io.gitlab.theevilskeleton.Upscaler
        - io.typora.Typora
        - it.mijorus.collector
        - it.mijorus.gearlever
        - it.mijorus.smile
        - md.obsidian.Obsidian
        - me.dusansimic.DynamicWallpaper
        - me.iepure.devtoolbox
        - net.nokyan.Resources
        - org.bluesabre.MenuLibre
        - org.gabmus.whatip
        - org.gaphor.Gaphor
        - org.gnome.Builder
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NetworkDisplays
        - org.gnome.PowerStats
        - org.gnome.Shotwell
        - org.gnome.Weather
        - org.gnome.World.PikaBackup
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.design.Contrast
        - org.gnome.design.Emblem
        - org.gnome.design.IconLibrary
        - org.gnome.design.Palette
        - org.gnome.design.SymbolicPreview
        - org.gnome.dspy
        - org.gnome.font-viewer
        - org.gnome.gitlab.YaLTeR.VideoTrimmer
        - org.gnome.seahorse.Application
        - org.inkscape.Inkscape
        - org.librehunt.Organizer
        - org.libreoffice.LibreOffice
        - org.nickvision.tubeconverter
        - page.codeberg.libre_menu_editor.LibreMenuEditor
        - re.sonny.Workbench

# Bundles --------------------------------------------------------------------

  # Pods (depends on podman-remote)
  - type: rpm-ostree
    install:
      - podman-remote
  - type: default-flatpaks
    user:
      install:
        - com.github.marhkb.Pods

  # Vaults (depends on gocryptfs)
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/gocryptfs/repo/fedora-%OS_VERSION%/pesader-gocryptfs-fedora-%OS_VERSION%.repo
    install:
      - gocryptfs
  - type: default-flatpaks
    user:
      install:
        - io.github.mpobaschnig.Vaults

# Shell tools ----------------------------------------------------------------

  # fzf
  - type: rpm-ostree
    install:
      - fzf
  - type: files
    files:
      - usr/etc/profile.d/fzf.sh: /usr/etc/profile.d/fzf.sh

  # zoxide
  - type: rpm-ostree
    install:
      - zoxide
  - type: files
    files:
      - usr/etc/profile.d/zoxide.sh: /usr/etc/profile.d/zoxide.sh

# Signing policy -------------------------------------------------------------

  - type: signing
