name: phos
description: A custom UBlue image for my own personal usage
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 43

modules:
  - from-file: install-rpmfusion.yml
  - from-file: remove-ublue-packages.yml
  - from-file: first-party-rpm-packages.yml
  - from-file: third-party-rpm-packages.yml
  - from-file: misc-installation-methods.yml
  - from-file: flatpaks-userwide.yml
  - from-file: bundles.yml
  - from-file: gtk3-theme.yml
  - from-file: shell-tools.yml
  - from-file: gnome-shell-extensions.yml
  - from-file: dotfiles.yml
  - from-file: gsettings.yml
  - from-file: signing.yml
