# image will be published to ghcr.io/<user>/<name>
name: ublue-custom
# description will be included in the image's metadata
description: My custom UBlue image, with support for Microsoft Surface hardware
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-surface
image-version: 39 # latest is also supported if you want new updates ASAP
# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr # copy static configurations
        #
        # copies config/files/usr into your image's /usr
        #
        # configuration you wish to end up in /etc/ on the booted system
        # should be added into /usr/etc/ as that is the proper "distro"
        # config directory on ostree. Read more in the files module's README
  - type: rpm-ostree
    repos:
      - https://repo.nextdns.io/nextdns.repo
      - https://copr.fedorainfracloud.org/coprs/dawid/gocryptfs/repo/fedora-39/dawid-gocryptfs-fedora-39.repo
      - https://copr.fedorainfracloud.org/coprs/pesader/showmethekey/repo/fedora-39/pesader-showmethekey-fedora-39.repo
    install:
      - btrfs-assistant
      - nautilus-python
      - neovim
      - nextdns
      - gocryptfs
      - guake
      - podman-remote
      - seahorse-nautilus
      - showmethekey
      - steam-devices
      - sushi
      - zsh
  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
      - add-firefox-pwa-repo.sh
  - type: rpm-ostree
    install:
      - firefoxpwa
