name: phos
description: A custom UBlue image for my own personal usage
base-image: ghcr.io/ublue-os/silverblue-surface
image-version: 39

# Just ----------------------------------------------------------------------

modules:
  - type: files
    files:
      - usr/share/ublue-os/just: /usr/share/ublue-os/just

# Akmods ---------------------------------------------------------------------

  - type: akmods
    install:
      - v4l2loopback

# Fonts ----------------------------------------------------------------------

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

# First-party RPM packages ---------------------------------------------------

  - type: rpm-ostree
    install:
      - adw-gtk3-theme
      - btrfs-assistant
      - gh
      - guake
      - nautilus-python
      - neovim
      - seahorse-nautilus
      - steam-devices
      - sushi
      - zsh

# Third-party RPM packages ---------------------------------------------------

  # awatcher
  - type: script
    scripts:
      - install-awatcher.sh

  # droidcam
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/meeuw/droidcam/repo/fedora-%OS_VERSION%/meeuw-droidcam-fedora-%OS_VERSION%.repo
    install:
      - droidcam

  # firefoxpwa
  - type: script
    scripts:
      - add-firefoxpwa-repo.sh
  - type: rpm-ostree
    install:
      - firefoxpwa

  # nextdns
  - type: rpm-ostree
    repos:
      - https://repo.nextdns.io/nextdns.repo
    install:
      - nextdns
  - type: script
    scripts:
      - setup-cache-in-nextdns.sh

  # showmethekey
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/pesader/showmethekey/repo/fedora-%OS_VERSION%/pesader-showmethekey-fedora-%OS_VERSION%.repo
    install:
      - showmethekey

  # yadm
  - type: rpm-ostree
    repos:
      - https://download.opensuse.org/repositories/home:TheLocehiliosan:yadm/Fedora_%OS_VERSION%/home:TheLocehiliosan:yadm.repo
    install:
      - yadm

# Flatpaks -------------------------------------------------------------------

  - type: default-flatpaks
    user:
      install:
        - app.drey.Warp
        - ca.desrt.dconf-editor
        - com.belmoussaoui.Authenticator
        - com.belmoussaoui.Decoder
        - com.belmoussaoui.Obfuscate
        - com.bitwarden.desktop
        - com.github.ADBeveridge.Raider
        - com.github.hluk.copyq
        - com.github.huluti.Curtail
        - com.github.jeromerobert.pdfarranger
        - com.github.tchx84.Flatseal
        - com.github.tenderowl.frog
        - com.mattjakeman.ExtensionManager
        - com.rafaelmardojai.SharePreview
        - com.stremio.Stremio
        - de.haeckerfelix.Fragments
        - io.github.celluloid_player.Celluloid
        - io.github.fabrialberio.pinapp
        - io.github.flattool.Warehouse
        - io.github.hrkfdn.ncspot
        - io.github.seadve.Kooha
        - io.github.slgobinath.SafeEyes
        - io.gitlab.adhami3310.Converter
        - io.gitlab.adhami3310.Footage
        - io.gitlab.adhami3310.Impression
        - io.gitlab.theevilskeleton.Upscaler
        - io.typora.Typora
        - it.mijorus.collector
        - it.mijorus.smile
        - me.dusansimic.DynamicWallpaper
        - me.iepure.devtoolbox
        - nl.hjdskes.gcolor3
        - org.gabmus.whatip
        - org.gaphor.Gaphor
        - org.gnome.Boxes
        - org.gnome.Builder
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Contacts
        - org.gnome.Evince
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.NetworkDisplays
        - org.gnome.Weather
        - org.gnome.World.PikaBackup
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.design.Emblem
        - org.gnome.design.IconLibrary
        - org.gnome.design.Palette
        - org.gnome.dspy
        - org.gnome.font-viewer
        - org.gnome.seahorse.Application
        - org.inkscape.Inkscape
        - org.librehunt.Organizer
        - org.libreoffice.LibreOffice
        - org.nickvision.tubeconverter
        - re.sonny.Workbench

# Bundles --------------------------------------------------------------------

  # openfortivpn (needs openfortivpn-webview)
  - type: rpm-ostree
    install:
      - openfortivpn
  - type: script
    scripts:
      - install-openfortivpn-webview.sh

  # Pods (depends on podman-remote)
  - type: rpm-ostree
    install:
      - podman-remote
  - type: default-flatpaks
    user:
      install:
        - com.github.marhkb.Pods

  # Vaults (depends on gocryptfs)
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/dawid/gocryptfs/repo/fedora-%OS_VERSION%/dawid-gocryptfs-fedora-%OS_VERSION%.repo
    install:
      - gocryptfs
  - type: default-flatpaks
    user:
      install:
        - io.github.mpobaschnig.Vaults

# Shell tools ----------------------------------------------------------------

  # fzf
  - type: rpm-ostree
    install:
      - fzf
  - type: files
    files:
      - usr/etc/profile.d/fzf.sh: /usr/etc/profile.d/fzf.sh

  # starship
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
  - type: files
    files:
      - usr/etc/profile.d/starship.sh: /usr/etc/profile.d/starship.sh

  # zoxide
  - type: rpm-ostree
    install:
      - zoxide
  - type: files
    files:
      - usr/etc/profile.d/zoxide.sh: /usr/etc/profile.d/zoxide.sh

# Signing policy -------------------------------------------------------------

  - type: script
    scripts:
      - signing.sh
